#!/usr/bin/env python3
"""
Created on Wed Sep 24 20:05:28 2025

@author: ghiggi
"""

import asyncio
from playwright.async_api import async_playwright
from pathlib import Path


async def main():
    url = "public/stations_map.html"  # local file generated by Folium
    output_path = Path("public/")
    output_path.mkdir(parents=True, exist_ok=True)
    screenshot_path = output_path / "map_preview.png"

    async with async_playwright() as p:
        browser = await p.chromium.launch()
        page = await browser.new_page()
        # Load the map (local file, so use file:// scheme)
        await page.goto(f"file://{Path(url).resolve()}")
        await page.set_viewport_size({"width": 800, "height": 500})
        await page.screenshot(path=str(screenshot_path))
        await browser.close()

    print(f"Saved preview at {screenshot_path}")


if __name__ == "__main__":
    asyncio.run(main())
